#!/usr/bin/env python3
"""Build a deterministic, offline BM25 index from the public-domain bundled BSB.

Run after rebuilding Bible.sqlite. No network, embeddings, or inference calls.
--check verifies that the checked-in index still matches its source database.
"""
import argparse
from collections import Counter, defaultdict
import gzip
import hashlib
import json
from pathlib import Path
import re
import sqlite3

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'Untitled Faith/Resources/Bible.sqlite'
OUTPUT = ROOT / 'backend/src/bible/data.ts'
CODES = ('GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH EZR NEH EST JOB PSA PRO ECC SNG '
         'ISA JER LAM EZK DAN HOS JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK LUK JHN ACT ROM '
         '1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV').split()


def build():
    db = sqlite3.connect(f'{SOURCE.as_uri()}?mode=ro', uri=True)
    meta = db.execute('SELECT id,name,license,notice,source FROM translation').fetchone()
    if not meta or meta[0] != 'BSB' or meta[2] != 'Public domain':
        raise SystemExit('Only the public-domain BSB may be included in this index.')
    verses = db.execute('SELECT id,text FROM verses ORDER BY id').fetchall()
    books = db.execute('SELECT id,name,chapters FROM books ORDER BY id').fetchall()
    db.close()
    # Share the app's existing, reviewed book aliases instead of maintaining a second list.
    swift = (ROOT / 'Untitled Faith/Services/Bible/BibleBook.swift').read_text()
    aliases = {int(i): [name, *json.loads(a)] for i, name, a in re.findall(r'BibleBook\(id: (\d+), name: "([^"]+)", aliases: (\[[^\]]*\])\)', swift)}
    if len(books) != 66 or len(aliases) != 66 or len(verses) < 30000:
        raise SystemExit('Expected the complete 66-book Bible and its book aliases.')
    postings = defaultdict(list)
    lengths = []
    for index, (_, text) in enumerate(verses):
        words = re.findall('[a-z]+', text.lower())
        lengths.append(len(words))
        for word, count in sorted(Counter(words).items()):
            postings[word].extend([index, count])
    data = {
        'translation': dict(zip(['id', 'name', 'license', 'notice', 'source'], meta)),
        'sourceSHA256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        'books': [dict(id=i, name=name, chapters=chapters, aliases=aliases[i], code=CODES[i-1]) for i, name, chapters in books],
        'verses': verses, 'lengths': lengths, 'averageLength': sum(lengths) / len(lengths),
        # Very common terms provide little retrieval value; still retained in verbatim text.
        'postings': {word: values for word, values in sorted(postings.items()) if len(values) / 2 < len(verses) * .2},
    }
    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    return '// Generated by scripts/bible/build-search.py. Do not edit. Public-domain BSB only.\n' + \
        'import type { BibleData } from "./types";\n' + \
        'export const bible: BibleData = JSON.parse(' + json.dumps(payload, ensure_ascii=False) + ');\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            raise SystemExit('Bible search index is stale. Run python3 scripts/bible/build-search.py')
        print('Bible search index matches its source database and book aliases.')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(result)
        print(f'Built BSB search index: {len(result.encode()):,} bytes; gzip {len(gzip.compress(result.encode())):,} bytes.')
